[package]
name = "test_helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
rsban_core = { path = "../../core" }
rsban_ledger = { path = "../../ledger" }
rsban_network = { path = "../../network" }
rsban_node = { path = "../../node", features = ["output_tracking"] }
rsban_nullable_tcp = { path = "../../nullables/tcp" }
rsban_rpc_client = { path = "../../rpc_client" }
rsban_rpc_server = { path = "../../rpc_server" }
rsban_websocket_server = { path = "../../websocket_server" }
mock_instant = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
axum = "0"
tracing-test = "0"
tokio = { version = "1" }
anyhow = "1"
