[package]
name = "rsban-insight"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui_extras = "0.29.1"
rsban_core = { path = "../../core" }
rsban_messages = { path = "../../messages" }
rsban_network = { path = "../../network" }
rsban_store_lmdb = { path = "../../store_lmdb" }
rsban_node = { path = "../../node" }
rsban_daemon = { path = "../../daemon" }
rsban_ledger = { path = "../../ledger" }
rsban_nullable_clock = { path = "../../nullables/clock" }
tokio = { version = "1", features = ["rt-multi-thread"] }
num-format = "0.4.4"
num = "0"
num-traits = "0"
num-derive = "0"
chrono = "0.4.19"
strum = "0"
