[package]
name = "rsban_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
rsban_core = { path = "../core" }
rsban_node = { path = "../node" }
rsban_rpc_server = { path = "../rpc_server" }
anyhow = "1"
tokio = { version = "1", features = ["signal"] }
